baseURL = "https://bigblank.co/"
languageCode = "en-us"
title = "Big Blank Startup Studio"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Contact Bigblank"
        url     = "/contact"
        weight  = 2
    #[[menu.nav]]
    #    name    = "Service"
    #    url     = "/service"
    #    weight  = 3 


# Site Params
[params]
    home = "Home"
    logo = "images/logo-sm.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "MAKE THE WORLD SMALLER"
        description = "WE INVEST IN MOBILITY RELATED PROJECTS - BIGBLANK"
        btn     = false
        btnText = "Download More"
        btnURL  = "https://bigblank.co/"
        [[params.banner.flipText]]
            title   = "TRAVEL"
        [[params.banner.flipText]]
            title   = "TRANSPORTATION"
        [[params.banner.flipText]]
            title   = "TOURISM"
        [[params.banner.flipText]]
            title   = "DELIVERY "

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT BIG BLANK"
        content = "Big Blank is a startup studio with one goal:  make the world smaller. We invest in mobility related projects, from logistics and transportation to travel entertainment."
        image   = "images/logo.png"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "CONTACT US ?"
        content = "If you are working on transportation subjects and want to join the team, we'd be happy to talk to you !"
        btnText = "Contact us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    